language: lisp

env:
  matrix:
    - LISP=ccl
    - LISP=ccl32
    - LISP=sbcl
    - LISP=sbcl32
    - LISP=cmucl
    - LISP=ecl

matrix:
  allow_failures:
    - env: LISP=cmucl
    - env: LISP=ecl

notifications:
  email:
    on_success: change
    on_failure: always

install:
  - if [ "$LISP" = "allegro" ]; then sudo apt-get install libc6-dev-i386 libffi-dev:i386; fi
  - sudo ./install-repo.bash
  - curl -L https://github.com/sionescu/cl-travis/raw/master/install.sh | sh
  - cl -e "(cl:in-package :cl-user)
           (dolist (p '(:alexandria :bordeaux-threads :fiveam))
             (ql:quickload p :verbose t))"
script:
  - cl -e "(cl:in-package :cl-user)
           (asdf/find-system:load-asd \"parfait.asd\")
           (asdf:load-system \"parfait/test\")
           (uiop:quit (if (some (lambda (x) (typep x '5am::test-failure))
                                (5am:run :iolib))
                          1 0))"